### ISSUE TITLE
Error:Execution failed for task ':app:externalNativeBuildDebug'

### ISSUE THREAD

**Issue by thanhfphan** [Lauszus/FaceRecognitionApp#1]
Error:unable to open output file 'D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/CapstoneProject/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'

Error:Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
Error while executing 'C:\Users\2TbP\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\CN9\Project\TaiLieu\FaceRecognitionApp\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=D:\CN9\Project\TaiLieu\FaceRecognitionApp\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\CN9\Project\TaiLieu\FaceRecognitionApp\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libface-lib.so}
[x86_64] Compile++      : face-lib <= face-lib.cpp
[x86_64] Compile++      : face-lib <= Facebase.cpp
error: unable to open output file 'D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'
1 error generated.
make: *** [D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o] Error 1

I followed your Build instructions but in this step i do not know how to config ndk-build. Help me pls

**Comment by Lauszus** [comment]
How did you clone the repository? You need to clone the submodule as well:
```bash
git clone --recursive https://github.com/Lauszus/FaceRecognitionApp.git
```
Then you should be able to build the code.

**Comment by thanhfphan** [comment]
I tried but it have same error.

>  Error:unable to open output file 'D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'
1 error generated.
make: *** [D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o] Error 1
:app:externalNativeBuildDebug FAILED
Error:Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
Error while executing 'C:\Users\2TbP\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\CN9\Project\TaiLieu\FaceRecognitionApp\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=D:\CN9\Project\TaiLieu\FaceRecognitionApp\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\CN9\Project\TaiLieu\FaceRecognitionApp\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libface-lib.so}
[x86_64] Compile++      : face-lib <= face-lib.cpp
[x86_64] Compile++      : face-lib <= Facebase.cpp
error: unable to open output file 'D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'
1 error generated.
make: *** [D:/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/CN9/Project/TaiLieu/FaceRecognitionApp/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o] Error 1

I use windows 7, does it affect??

**Comment by Lauszus** [comment]
Try to hardcode the path to OpenCV and Eigen here: https://github.com/Lauszus/FaceRecognitionApp/blob/master/app/src/main/cpp/Android.mk#L6 and https://github.com/Lauszus/FaceRecognitionApp/blob/master/app/src/main/cpp/Android.mk#L12 respectively.

**Comment by andy1945** [comment]
I had same issue but i had to hard code the path for opencv and Eigen

**Comment by Lauszus** [comment]
@andy1945 I assume you are using Windows as well? I have tested setting the environmental variables in both Linux and Mac and works well.

**Comment by Lauszus** [comment]
Please see the updates build instructions: <https://github.com/Lauszus/FaceRecognitionApp#build-instructions>.
