### ISSUE TITLE
Some information and Automatic recognition.

### ISSUE THREAD

**Issue by Angelk90** [Lauszus/FaceRecognitionApp#10]
@Lauszus : First of all, I wanted to congratulate you on the module.
I wanted to ask you some questions:

1)
I have found to do train to the algorithm, but often I can detect a face that is not there, that gives me a name of those that are already set (most of the time the first set) to objects that they do not own it, for example a plastic cup.

2)
The take picture done on objects that have a face, but are not real people supposed to work or not?
For example, I take a photo or take a picture from google and do I take the picture to it should work or not?

3)
Do not consider that there may be more subjects in the picture, right?
If there are two faces in the picture, which one do you consider?

4)
It would be possible to add the following as a new feature:
If a face is recognized, it puts a colored square on the face of the subject with its own name, without having to press the take picture to check who it is.
link: https://lh3.googleusercontent.com/JEHioSiUNLGqso2-jGoNzbkQ4w_LHWN-MrchP3w3-4lY69QOtKbetUuXdFAOElLD98g=h900

**Comment by Lauszus** [comment]
1. You can adjust the "Face threshold". Increasing this threshold would result in a fewer objects as being detected as faces.
2. Yes, this algorithm does not care if the picture is from photo or a "real" person.
3. No, the current code assumes that there is only one face in the frame.
4. You should look into the following example: https://github.com/opencv/opencv/tree/master/samples/android/face-detection. It does exactly what you want. Note that it is not something I will be working on.
