### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by PulkitAppz** [Lauszus/FaceRecognitionApp#16]
```
Error:(21, 10) fatal error: 'Eigen/Dense' file not found
```
I already set the path as u suggested but not able to build the code .What should i need to change to make it run?

**Comment by Lauszus** [comment]
Please post the full content of Android.mk. Also see #15.

Alternatively you can try to hardcode the paths to OpenCV and Eigen3.

**Comment by sparxapps** [comment]
@PulkitAppz In my case, I have replaced 
`#include <Eigen/Dense>`
to
`#include </home/demo/Workspace_Android_Studio/Samples/eigen-eigen-67e894c6cd8f/Eigen/Dense>`

**Comment by Lauszus** [comment]
Please follow the instructions in the README. Either you have to set the environmental variables or hardcode the paths in [Android.mk](https://github.com/Lauszus/FaceRecognitionApp/blob/master/app/src/main/cpp/Android.mk).

**Comment by arifdel** [comment]
It working perfectly. I tried all the scenario and i found lots of issue in the recognition like after few face get trained and if there is no one in the picture the still it shows face found and similarly when there is a person in the frame still it shows not a face.

**Comment by Lauszus** [comment]
Closing this issue, as the project build fine when following the build instructions.

**Comment by Lauszus** [comment]
I have now setup a Travis build to automatically upload a zip directory of the project including all the dependencies. This should make much easier for people to compile the project.

You can try it out at the following link: <https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.1/FaceRecognitionApp-1.2.1.zip>.

**Comment by Aashima-Gupta** [comment]
Hey! can you tell how this Part of code is working:

```java
protected Bundle doInBackground(Mat... mat) {
    float[] minDist = new float[] { -1 };
    int[] minDistIndex = new int[1];
    float[] faceDist = new float[1];
    try {
       MeasureDist(mat[0].getNativeObjAddr(), minDist, minDistIndex, faceDist, useEigenfaces);
    } catch (Exception e) {
       error = e;
       return null;
    }
    Bundle bundle = new Bundle();
    bundle.putFloat(MIN_DIST_FLOAT, minDist[0]);
    bundle.putInt(MIN_DIST_INDEX_INT, minDistIndex[0]);
    bundle.putFloat(DIST_FACE_FLOAT, faceDist[0]);
    return bundle;
}
```

**Comment by Lauszus** [comment]
@Aashima-Gupta please stop spamming all the issues. That won't help you getting my attention...
