### ISSUE TITLE
on installing project it gives on gradle finish

### ISSUE THREAD

**Issue by shahbazashraf** [Lauszus/FaceRecognitionApp#19]
Error:unable to open output file 'C:/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/face-lib/C_/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.2.2/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'

**Comment by shahbazashraf** [comment]
please help i can't find what is issue i searched alot

**Comment by Lauszus** [comment]
Did you follow the build instructions: https://github.com/Lauszus/FaceRecognitionApp#build-instructions?

Also is that the full build error? Please post it in full.

**Comment by shahbazashraf** [comment]
it gives this when i run the command in command line.

C:\Users\ShahbazKhan\Downloads\Compressed\FaceRecognitionApp-1.2.2>git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git

**Comment by shahbazashraf** [comment]
for this as well not operating the command lines..any help what i am doing wrong
C:\Users\ShahbazKhan\Downloads\Compressed\FaceRecognitionApp-1.2.2>wget https://github.com/opencv/opencv/releases/download/3.4.1/opencv-3.4.1-android-sdk.zip
'wget' is not recognized as an internal or external command,
operable program or batch file.

**Comment by shahbazashraf** [comment]
**first build successfully done then when i run the app then after gradle build it gives...**

Error:unable to open output file 'C:/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/face-lib/C_/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.2.2/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'

**Comment by Lauszus** [comment]
Please do __NOT__ follow the "Advanced build instructions", just download the latest release: <https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.2/FaceRecognitionApp-1.2.2.zip>, unzip it and then open it using Android Studio.

**Comment by shahbazashraf** [comment]
yes that's what i have done..but after successful first build when i run application for installation on mobile it gives this error..i don't know what is file or directory missing name **Facebas.o**.

**error**
Error:unable to open output file 'C:/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/face-lib/C_/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.2.2/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'

**Comment by shahbazashraf** [comment]
i tried to find file of given path but didn't find..what is error

**Comment by Lauszus** [comment]
I just tried it myself. The project builds fine. Please make sure that you have install Android NDK and that Android Studio is up to date. Have you modified any files?

**Comment by shahbazashraf** [comment]
yes i have installed NDK and also i didn't modified any file..
i also got the first build right means project build fine but when i run
project for installation then it gives this error..FaceBase.o file or
directory not found

**Comment by Lauszus** [comment]
Can you try to compile it from the command line:

Unix:
```bash
./gradlew
```

Windows:
```bash
gradlew.bat
```

**Comment by shahbazashraf** [comment]
ok i will try.. But sir if you run a code and install an application if it working can you share that code with me  i will be thankfull..waiting

**Comment by Lauszus** [comment]
It is working here. You can download the compiled APK under the release tab: https://github.com/Lauszus/FaceRecognitionApp/releases.

**Comment by shahbazashraf** [comment]
sir i have done **gradlew.bat** 
it said **BUILD FAILED in 2m 15s**

**Comment by Lauszus** [comment]
Can you try to install the APK and see if that works on your device?

**Comment by Lauszus** [comment]
Just download and install the universal APK on your device: <https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.2/FaceRecognitionApp-1.2.2-universal-release.apk>.

**Comment by shahbazashraf** [comment]
now its successful BUILD SUCCESSFUL in 3m 1s

**Comment by Lauszus** [comment]
Okay. I believe we can close this issue then, as it sounds like it was an issue on your side and not with the code.

**Comment by shahbazashraf** [comment]
Error:unable to open output file 'C:/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.3.0-dev/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/face-lib/C_/Users/ShahbazKhan/Downloads/Compressed/FaceRecognitionApp-1.3.0-dev/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'

i have tried the new version as well it also have same error...do know how i fix **Facebase.o': 'No such file or directory'**

**Comment by shahbazashraf** [comment]
sir i am able to install the application..
the issue is the for that file is too long thats why project is not creating the correct path 
i have solved it by changing the project location

**Comment by Lauszus** [comment]
Okay good to hear that. Seem like a known issue on Windows: https://stackoverflow.com/questions/33905687/error-file-path-too-long-on-windows-keep-below-240-characters.

I will close this issue now since you got it working :)

**Comment by shahbazashraf** [comment]
yes broo but know in project application closed while recognition and it
says..
*StaticHelper: OpenCV error: Cannot load info library for OpenCV*
*i also added the latest sdk of open cv..any idea*

**Comment by shahbazashraf** [comment]
it also closes the application that when i switch between camera to train
two two different faces..why if application closed one it never opened again

**Comment by Lauszus** [comment]
Please do not update anything until you have got it working. Did you ever try installing the APK?

**Comment by shahbazashraf** [comment]
not yet but need your code to  understand need to on other project..

**Comment by Lauszus** [comment]
Yes, but it would help me quite a lot if I would know if it was your phone or your setup that was the problem, so please try the APK.
