### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by liaoweiguo** [Lauszus/FaceRecognitionApp#20]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :opencv.

Already hardcode the opencv path in app Android.mk

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

OPENCV_INSTALL_MODULES := on
include /media/xx/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk

LOCAL_MODULE := face-lib
LOCAL_SRC_FILES += $(LOCAL_PATH)/face-lib.cpp $(LOCAL_PATH)/FaceRecognitionLib/Facebase.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/Eigenfaces.cpp $(LOCAL_PATH)/FaceRecognitionLib/Fisherfaces.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/PCA.cpp $(LOCAL_PATH)/FaceRecognitionLib/LDA.cpp
LOCAL_C_INCLUDES += /media/xx/eigen
LOCAL_C_INCLUDES += $(LOCAL_PATH)/FaceRecognitionLib/RedSVD/include
LOCAL_LDLIBS += -llog -ldl
LOCAL_CPPFLAGS += -std=gnu++11 -frtti -fexceptions

include $(BUILD_SHARED_LIBRARY)

**Comment by Lauszus** [comment]
You need to modify this file as well: https://github.com/Lauszus/FaceRecognitionApp/blob/master/settings.gradle

**Comment by liaoweiguo** [comment]
Thanks. Great jobs!

**Comment by Lauszus** [comment]
I have now updated the build documentation: <https://github.com/Lauszus/FaceRecognitionApp/commit/4560b8396011bb95308192b2851be47060a95c02>. Thanks for the feedback.
