### ISSUE TITLE
Getting following error after import project and follow all the steps

### ISSUE THREAD

**Issue by skynetandroiddev** [Lauszus/FaceRecognitionApp#22]
```
Build command failed.


Error while executing process /Users/bhachu/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/bhachu/FaceRecognitionApp/app/src/main/cpp/Android.mk NDK_APPLICATION_MK=/Users/bhachu/FaceRecognitionApp/app/src/main/cpp/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=/Users/bhachu/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/bhachu/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


*** Android NDK: APP_STL gnustl_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
Open File


Build command failed.


Error while executing process /Users/bhachu/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/bhachu/FaceRecognitionApp/app/src/main/cpp/Android.mk NDK_APPLICATION_MK=/Users/bhachu/FaceRecognitionApp/app/src/main/cpp/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/Users/bhachu/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/bhachu/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


*** Android NDK: APP_STL gnustl_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
Open File


Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :opencv.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :opencv.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :opencv.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :opencv.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :opencv.
Open File
Show Details
```

**Comment by Lauszus** [comment]
Please follow the simple build instructions. From your errors messages I would guess that you have not added the OpenCV library properly.

But please follow the simple build instructions and get the code compiling first before attempting the advanced build instructions.

**Comment by skynetandroiddev** [comment]
I just simply follow below rules

First clone the repository including the submodule:
git clone --recursive https://github.com/Lauszus/FaceRecognitionApp.git
If you have already cloned the project, then please run the following command in order to initialize the submodule:
git submodule update --init --recursive
The project is relying on the environmental variables OPENCV_ANDROID_SDK and EIGEN3_DIR for settings.gradle and Android.mk to be set to the path of the OpenCV Android SDK and Eigen3 libraries.
Please use OpenCV 3.4.1 and Eigen3 3.3.4. Both can be installed from the command line like so:
wget https://github.com/opencv/opencv/releases/download/3.4.1/opencv-3.4.1-android-sdk.zip
unzip opencv-3.4.1-android-sdk.zip
wget https://bitbucket.org/eigen/eigen/get/3.3.4.zip -O Eigen3.zip
unzip Eigen3.zip
Now simple set the environmental variables:

Mac:
nano /etc/launchd.conf
setenv OPENCV_ANDROID_SDK /path/to/OpenCV-android-sdk
setenv EIGEN3_DIR /path/to/eigen3
echo $OPENCV_ANDROID_SDK $EIGEN3_DIR

**Comment by Lauszus** [comment]
As I wrote before, please follow the simple build instructions first: https://github.com/Lauszus/FaceRecognitionApp/blob/master/README.md#build-instructions.

**Comment by skynetandroiddev** [comment]
I download this demo. Now only get this error. Please let me know what to do?
```
Build command failed.


Error while executing process /Users/bhachu/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/src/main/cpp/Android.mk NDK_APPLICATION_MK=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/src/main/cpp/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/debug/lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


***** Android NDK: APP_STL gnustl_static is no longer supported.** Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
Open File


Build command failed.


Error while executing process /Users/bhachu/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/src/main/cpp/Android.mk NDK_APPLICATION_MK=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/src/main/cpp/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/bhachu/Downloads/FaceRecognitionApp-1.2.2/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


*** Android NDK: APP_STL gnustl_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
Open File
```

**Comment by Lauszus** [comment]
@skynetandroiddev try replacing ```gnustl_static``` with ```c++_static``` at these lines:

https://github.com/Lauszus/FaceRecognitionApp/blob/4560b8396011bb95308192b2851be47060a95c02/app/build.gradle#L13

https://github.com/Lauszus/FaceRecognitionApp/blob/4560b8396011bb95308192b2851be47060a95c02/app/src/main/cpp/Application.mk#L3

**Comment by Lauszus** [comment]
Looks like gnustl has been removed in Android NDK r18: <https://developer.android.com/ndk/downloads/revision_history>.

I'll release a fix shortly.

Thanks for the report.

**Comment by skynetandroiddev** [comment]
After change `gnustl_static` to `c++_static` it'll work fine. Thanks.

**Comment by alokmishraqaz** [comment]
Build command failed.


Error while executing process C:\Users\Admin\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Admin\AndroidStudioProjects\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\Admin\AndroidStudioProjects\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=C:/Users/Admin/AndroidStudioProjects/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\Users\Admin\AndroidStudioProjects\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


process_begin: CreateProcess(NULL, "", ...) failed.


*** Android NDK: APP_STL c++_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
Open File


Build command failed.


Error while executing process C:\Users\Admin\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Admin\AndroidStudioProjects\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\Admin\AndroidStudioProjects\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/Admin/AndroidStudioProjects/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Admin\AndroidStudioProjects\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


process_begin: CreateProcess(NULL, "", ...) failed.


*** Android NDK: APP_STL c++_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
Open File

**Comment by alokmishraqaz** [comment]
even After changing gnustl_static to c++_static it is still showing this error

**Comment by nagdawi** [comment]
Simple instruction https://github.com/Lauszus/FaceRecognitionApp/blob/master/README.md#build-instructions run fine with me after update the code with `c++_static ` . this work only with emluator but it's not work with real device 

```
C:/Users/Nagdawi/Documents/faceRecoApp2/FaceRecognitionApp-1.2.2/app/src/main/cpp/face-lib.cpp:70: error: undefined reference to 'Fisherfaces::train(Eigen::Matrix<int, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, 1, 0, -1, 1> const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
```
