### ISSUE TITLE
Could not find lint-gradle-api.jar

### ISSUE THREAD

**Issue by 0x13A0F** [Lauszus/FaceRecognitionApp#26]
I followed the simple build instruction, but when opening the project, i get this error when building:

`Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
`

**Comment by Lauszus** [comment]
Could you try to swap the order of ```jcenter()``` and ```google()``` in [build.gradle](https://github.com/Lauszus/FaceRecognitionApp/blob/master/build.gradle) i.e:

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by nagdawi** [comment]
I try this solution but it doesn't work

```
buildscript {
    repositories {
        google()
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by Lauszus** [comment]
I just released a new version. Please try the newest zip file: https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.3/FaceRecognitionApp-1.2.3.zip and reopen this issue if it is not fixed.
