### ISSUE TITLE
when i try to run app from android studio getting error on this project

### ISSUE THREAD

**Issue by Jaimin7632** [Lauszus/FaceRecognitionApp#28]
Error:error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Lauszus** [comment]
Which version are you trying to compile? Please also post the full error code.

**Comment by Jaimin7632** [comment]
I just only get error which i already posted. Is there any error in
Android.mk file. or else there a probelm in graddle for minsdk or compile sdk ??

And also getting this warning...

Warning:ABIs [armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.

**Comment by Jaimin7632** [comment]
i got the solution. there a problem in $(LOCAL_PATH) which are u declare in android.mk file .
thanks for your support .btw  great work.

**Comment by Lauszus** [comment]
Good to hear you got it working.

**Comment by Pittu7** [comment]
Hi Jaimin
Can I please know how did you fix the warning message?

**Comment by Jaimin7632** [comment]
Correct path in android.mk files. Please ckeck it and try again.

**Comment by Pittu7** [comment]
I am using windows 10.
Do I need to replace the local path as shown below:
_OPENCV_INSTALL_MODULES := on
include C:/Users/Administrator/FaceRecognitionApp-1.2.3/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk_

**Comment by Jaimin7632** [comment]
Yup also check out the opencv version are you using . Check the azure face
api android. You find your solution there.

**Comment by Pittu7** [comment]
do I have to change the local paths for all the values as such in android.mk?
Am using OpenCV 3.4.1 just as the one used in this project

**Comment by Jaimin7632** [comment]
Yes

**Comment by Pittu7** [comment]
Build is getting failed when am trying to update my local path for all the values
