### ISSUE TITLE
Toasting Last Value

### ISSUE THREAD

**Issue by ifanfaizal** [Lauszus/FaceRecognitionApp#34]
After training the Eigenface with my face, I took another object images which not a face but I got the same value on toast "face detected: (my name)" which is not corrent answer. I'm using face and distance threshold 0.251 btw. Thanks Lauszus :+1:

**Comment by Lauszus** [comment]
The algorithm is far from perfect. Please note that Eigenfaces and Fisherfaces are not state of the art. If you want to get a higher success-rate you should look into machine learning or similar.
