### ISSUE TITLE
Need to remove the fisherfaces

### ISSUE THREAD

**Issue by javdi** [Lauszus/FaceRecognitionApp#35]
Hello sir,
 Can you provide me the app which only has eigenfaces and not the fisherfaces, please sir I need to show it to the college, as iam doing a project over it, please sir I need a app only does eigenfaces and it's source code

**Comment by Lauszus** [comment]
Simply comment out the ```RadioGroup``` at these lines: 

https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/res/layout/activity_face_recognition_app.xml#L39-L59

and the comment out the following code: 

https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L297-L329

And then hardcode the ```useEigenfaces``` variable:

```java
useEigenfaces = True
```

**Comment by Pittu7** [comment]
Hello Javdi
Can I please know how did you do this:
_And then hardcode the useEigenfaces variable:

useEigenfaces = True_
