### ISSUE TITLE
Error facebase.o unable to run the project

### ISSUE THREAD

**Issue by fatkharrofiqi** [Lauszus/FaceRecognitionApp#36]
I'm using this https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.3/FaceRecognitionApp-1.2.3.zip, and got this error, pls help me

error: unable to open output file 'D:/Mobile-Developments/Projects/Android-Native/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/Mobile-Developments/Projects/Android-Native/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'
1 error generated.
make: *** [D:/Mobile-Developments/Projects/Android-Native/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/D_/Mobile-Developments/Projects/Android-Native/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Facebase.o] Error 1

**Comment by Lauszus** [comment]
This is a issue with Windows. Please see: https://github.com/Lauszus/FaceRecognitionApp/issues/19#issuecomment-400646148 and https://stackoverflow.com/questions/33905687/error-file-path-too-long-on-windows-keep-below-240-characters.
