### ISSUE TITLE
Accuracy issue

### ISSUE THREAD

**Issue by Kinwong1103** [Lauszus/FaceRecognitionApp#37]
Hi sir, I’ve successfully implemented your project into my Android application. However, the performance is not as well as I expected.

Can you please explain briefly the meaning of face threshold and distance threshold? How should i modify them to improve performance?

**Comment by Lauszus** [comment]
@Kinwong1103 please see: https://github.com/Lauszus/FaceRecognitionApp/issues/14#issuecomment-359169694.
