### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by alike123** [Lauszus/FaceRecognitionApp#40]
# Unable to resolve dependency
Thanks for your work! I'm working with android studio 3.1.2. And I have install opencv_android_sdk and hardcode in those two files. And another question. If I also need to import the opencv lib into this project manually?

`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :opencv.

Open File
Show Details`

**Comment by Lauszus** [comment]
Please just download the latest release where everything has been taken care of: https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.3/FaceRecognitionApp-1.2.3.zip

This is also described in the build instructions: https://github.com/Lauszus/FaceRecognitionApp#build-instructions.

**Comment by aznj** [comment]
Thank you for this. Excellent work.
