### ISSUE TITLE
App crashed with Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by jamenenedez** [Lauszus/FaceRecognitionApp#42]
Hi, I am using the app for school work and I needed to add another functionality. This functionality is for web scrapping. I was using eigen face component, and it works fine, but when I decided to use fisher face component the app crash just when I return from the activity I added. The crash message was:

"A/libc: app/src/main/cpp/FaceRecognitionLib/LDA.cpp:45: int32_t LDA::compute(const Eigen::MatrixXf &, const Eigen::VectorXi &, int32_t): assertion "(size_t)classes.size() == N" failed
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 3583 (AsyncTask #3), pid 2845 (erecognitionapp)"

**Comment by Lauszus** [comment]
It crashes at the following line: https://github.com/Lauszus/FaceRecognitionLib/blob/e4f211b9935c3d5bc0df408a46183aaf9c446cdf/LDA.cpp#L45, as per the comment it makes sure that there is a "class for each column". So it looks like you have not generated your classes vector correctly in your application.

Please take a look at how it is done in the app:
https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L142-L169

**Comment by jamenenedez** [comment]
I reviewed my code one more time and uncomment 
`
/*for (int i = 0; i < imagesLabels.size(); i++) 
                 Log.i(TAG, "Classes: " + imagesLabels.get(i) + " = " + classes[i]);*/
`  
After that I saw this: 
```
2019-08-03 11:25:55.093 8859-8859/com.lauszus.facerecognitionapp I/FaceRecognitionAppActivity: Classes: Jesús favela vara = 1
2019-08-03 11:25:55.093 8859-8859/com.lauszus.facerecognitionapp I/FaceRecognitionAppActivity: Classes: Gustavo olague caballero = 2
2019-08-03 11:25:55.093 8859-8859/com.lauszus.facerecognitionapp I/FaceRecognitionAppActivity: Classes: Jesús favela vara = 1
2019-08-03 11:25:55.093 8859-8859/com.lauszus.facerecognitionapp I/FaceRecognitionAppActivity: Classes: Jesús favela vara = 1
```

Then I figured out that it was fine but once it runs 
```
assert((size_t)classes.size() == N); // Make sure that there is a class for each column 
```
the app crash. So, what can I do?

**Comment by Lauszus** [comment]
What is the output of this line: https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L133

**Comment by jamenenedez** [comment]
The output was:

2019-08-05 09:20:58.971 1071-1071/com.lauszus.facerecognitionapp
I/FaceRecognitionAppActivity: Images height: 40000 Width: 13 total: 520000
2019-08-05 09:21:20.876 1071-1071/com.lauszus.facerecognitionapp
I/FaceRecognitionAppActivity: Images height: 40000 Width: 1 total: 40000
2019-08-05 09:21:40.519 1071-1071/com.lauszus.facerecognitionapp
I/FaceRecognitionAppActivity: Images height: 40000 Width: 2 total: 80000
2019-08-05 09:21:53.306 1071-1071/com.lauszus.facerecognitionapp
I/FaceRecognitionAppActivity: Images height: 40000 Width: 3 total: 120000
2019-08-05 09:22:03.838 1071-1071/com.lauszus.facerecognitionapp
I/FaceRecognitionAppActivity: Images height: 40000 Width: 4 total: 160000
2019-08-05 09:22:07.617 1071-1071/com.lauszus.facerecognitionapp
I/FaceRecognitionAppActivity: Images height: 40000 Width: 5 total: 200000

**Comment by jamenenedez** [comment]
I've got this other issue:

A/libc: libs\eigen-eigen\Eigen/src/Core/CwiseBinaryOp.h:110:
Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>,
const Eigen::CwiseUnaryOp<Eigen::internal::scalar_cast_op<int, float>,
const Eigen::Matrix<int, -1, -1, 0, -1, -1> >, const
Eigen::Replicate<Eigen::Matrix<float, -1, 1, 0, -1, 1>, 1, -1>
>::CwiseBinaryOp(const Eigen::CwiseBinaryOp::Lhs &, const
Eigen::CwiseBinaryOp::Rhs &, const BinaryOp &) [BinaryOp =
Eigen::internal::scalar_difference_op<float, float>, LhsType = const
Eigen::CwiseUnaryOp<Eigen::internal::scalar_cast_op<int, float>, const
Eigen::Matrix<int, -1, -1, 0, -1, -1> >, RhsType = const
Eigen::Replicate<Eigen::Matrix<float, -1, 1, 0, -1, 1>, 1, -1>]: assertion
"aLhs.rows() == aRhs.rows() && aLhs.cols() == aRhs.cols()" failed
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 1586 (AsyncTask
#3), pid 1071 (erecognitionapp)

**Comment by Lauszus** [comment]
Please post the output of both the image size and the classes, so I can confirm that you have done it correctly.

You need to make sure that the width of the image is equal to the number of classes.

**Comment by Lauszus** [comment]
I'm closing this due to a lack of response. Feel free to reopen if you still are having issues.

**Comment by umairkhalid-bim** [comment]
@Lauszus Thank you so much for writing this beautiful library for Android developers. I am facing same issue. It works absolutely fine when I capture image from camera 

https://github.com/Lauszus/FaceRecognitionApp/blob/0cdb1dbb8159fe43170b2ca66ae62c63634785a7/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L380

but when I manually try to load image from gallery to train it gives main this error.

I have pasted code for where I am trying to train my own image 

 ```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        NativeMethods.MeasureDistTask mMeasureDistTask = null;

        if(requestCode == RESULT_LOAD_IMAGE && resultCode == RESULT_OK){
            Uri imageUri = data.getData();
            try {


                if (mMeasureDistTask != null && mMeasureDistTask.getStatus() != AsyncTask.Status.FINISHED) {
                    Log.i(TAG, "mMeasureDistTask is still running");
                    showToast("Still processing old image...", Toast.LENGTH_SHORT);
                    return;
                }
                if (mTrainFacesTask != null && mTrainFacesTask.getStatus() != AsyncTask.Status.FINISHED) {
                    Log.i(TAG, "mTrainFacesTask is still running");
                    showToast("Still training...", Toast.LENGTH_SHORT);
                    return;
                }

                Bitmap bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), imageUri);

                Mat m = new Mat(200, 200 , CvType.CV_8U);

                //m = Imgcodecs.imread(getPath(FaceRecognitionAppActivity.this, data.getData()));
                Utils.bitmapToMat(bitmap, m);


                Log.e(TAG, "M Gray height: " + m.height() + " Width: " + m.width() + " total: " + m.total());
                if (m.total() == 0)
                    return;

                // Scale image in order to decrease computation time and make the image square,
                // so it does not crash on phones with different aspect ratios for the front
                // and back camera

                //SaveImage(mGray);

                Imgproc.cvtColor(m, m, Imgproc.COLOR_RGB2GRAY);
                m.convertTo(m, CvType.CV_8U); //Just to match camera images


                Size imageSize = new Size(200, 200);
                Imgproc.resize(m, m, imageSize);
                Log.e(TAG, "M Small gray height: " + m.height() + " Width: " + m.width() + " total: " + m.total());
                //SaveImage(mGray);

                Mat image = m.reshape(0, (int) m.total());


                // Create column vector
                Log.e(TAG, "M Vector height: " + image.height() + " Width: " + image.width() + " total: " + image.total());
                images.add(image); // Add current image to the array

                if (images.size() > maximumImages) {
                    images.remove(0); // Remove first image
                    imagesLabels.remove(0); // Remove first label
                    Log.i(TAG, "The number of images is limited to: " + images.size());
                }

                // Calculate normalized Euclidean distance
                mMeasureDistTask = new NativeMethods.MeasureDistTask(useEigenfaces, measureDistTaskCallback);
                mMeasureDistTask.execute(image);

                showLabelsDialog();
//


                //images.add(m);
               // imagesLabels.add("Umair");


            } catch (IOException e) {
                e.printStackTrace();
            }

//            imgView.setImageURI(imageUri);
        }
    }
```
