### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by Hubert1403** [Lauszus/FaceRecognitionApp#45]
Build command failed.
Error while executing process C:\Users\Raquel\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Raquel\Downloads\FaceRecognitionApp-1.2.3\FaceRecognitionApp-1.2.3\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\Raquel\Downloads\FaceRecognitionApp-1.2.3\FaceRecognitionApp-1.2.3\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Raquel\Downloads\FaceRecognitionApp-1.2.3\FaceRecognitionApp-1.2.3\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libface-lib.so}
[x86_64] Compile++      : face-lib <= face-lib.cpp
[x86_64] Compile++      : face-lib <= Facebase.cpp
[x86_64] Compile++      : face-lib <= Eigenfaces.cpp
[x86_64] Compile++      : face-lib <= Fisherfaces.cpp
[x86_64] Compile++      : face-lib <= PCA.cpp
[x86_64] Compile++      : face-lib <= LDA.cpp
[x86_64] Prebuilt       : libopencv_java3.so <= C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/../../../../OpenCV-android-sdk/sdk/native/jni/../libs/x86_64/
[x86_64] SharedLibrary  : libface-lib.so

C:/Users/Raquel/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld: error: cannot open C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/C_/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Facebase.o: No such file or directory
C:/Users/Raquel/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld: error: cannot open C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/C_/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Eigenfaces.o: No such file or directory
C:/Users/Raquel/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld: error: cannot open C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/C_/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Fisherfaces.o: No such file or directory
C:/Users/Raquel/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld: error: cannot open C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/C_/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/PCA.o: No such file or directory
C:/Users/Raquel/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld: error: cannot open C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib/C_/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/LDA.o: No such file or directory
C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/face-lib.cpp:62: error: undefined reference to 'Eigenfaces::train(Eigen::Matrix<int, -1, -1, 0, -1, -1> const&)'
C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/face-lib.cpp:70: error: undefined reference to 'Fisherfaces::train(Eigen::Matrix<int, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, 1, 0, -1, 1> const&)'
C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/face-lib.cpp:103: error: undefined reference to 'Facebase::project(Eigen::Matrix<int, -1, -1, 0, -1, -1> const&)'
C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/face-lib.cpp:105: error: undefined reference to 'Facebase::reconstructFace(Eigen::Matrix<float, -1, 1, 0, -1, 1> const&)'
C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/face-lib.cpp:108: error: undefined reference to 'Facebase::euclideanDistFace(Eigen::Matrix<int, -1, 1, 0, -1, 1> const&, Eigen::Matrix<float, -1, 1, 0, -1, 1> const&)'
C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/src/main/cpp/face-lib.cpp:112: error: undefined reference to 'Facebase::euclideanDist(Eigen::Matrix<float, -1, 1, 0, -1, 1> const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/Raquel/Downloads/FaceRecognitionApp-1.2.3/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libface-lib.so] Error 1

this is the error I get when running the project
any clues?

**Comment by Lauszus** [comment]
@Hubert1403 sounds like you are hitting this Windows issue: https://github.com/Lauszus/FaceRecognitionApp/issues/19#issuecomment-400646148. Can you try to put the project somewhere with a shorter path?

**Comment by Lauszus** [comment]
I'm closing this due to a lack of response. Feel free to reopen if you still are having issues.
