### ISSUE TITLE
Can not build the project..

### ISSUE THREAD

**Issue by shahnizarbaloch** [Lauszus/FaceRecognitionApp#46]
When I have imported every required library like openCV etc then it has been synchronized successfully but when i try to build the APK file of it then it shows the error, (unable to open output file)

**Comment by Lauszus** [comment]
@shahnizarbaloch please post the full error log.

**Comment by shahnizarbaloch** [comment]
When I have compiled the project, there was no error, which is shown in picture 1
![1](https://user-images.githubusercontent.com/28158590/64486518-9ec91500-d247-11e9-9ad2-85f1e1aac619.jpg)
but when i try to build the apk then this error is shown.
![2](https://user-images.githubusercontent.com/28158590/64486525-a7b9e680-d247-11e9-9b23-a31c8a697bcb.jpg)

**Comment by Lauszus** [comment]
Please make sure that you do let Android Studio update Gradle etc. Also please make sure that you are using the newest version of Android Studio.

**Comment by shahnizarbaloch** [comment]
I have done everything bro.. I don't know why it is happenning! well, i will try again.

**Comment by gabrielbrandaodelima** [comment]
I've got the same problem, did you manage to fix it?

**Comment by shahnizarbaloch** [comment]
> 
> 
> I've got the same problem, did you manage to fix it?

no, I couldn't fix it dear. I have tried everything but still, I couldn"t do it.

**Comment by gabrielbrandaodelima** [comment]
> > I've got the same problem, did you manage to fix it?
> 
> no, I couldn't fix it dear. I have tried everything but still, I couldn"t do it.

I did!

Just change the path of your project to a smaller one. It looks like the path must be 240 characters long. I've moved it to "C:\" only, and it worked!

**Comment by Lauszus** [comment]
@gabrielbrandaodelima yes this is a known issue with Windows: https://github.com/Lauszus/FaceRecognitionApp/issues/19#issuecomment-400646148. There is nothing I can do about it.
