### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by ramvdixit** [Lauszus/FaceRecognitionApp#47]
Hi,

I went about building the app using the advanced instructions.. I downloaded the OpenCV SDK and Eigen package and I set the environment variables as well. I downloaded the FaceRecognitionApp project and when I try to build it (with Android Studio), I keep getting the following build output (pasted below). Can you please give me some pointers? Here are some details:

1. OpenCV SDK is in a folder in the C drive. (path: C:\OpenCV-android-sdk)
2. Eigen is in a folder in the C drive (path: C:\eigen-eigen-323c052e1731)
3. The FaceRecognitionApp project is in E Drive (path: E:\HDev2\fra\FaceRecognitionApp)
4. Environment Variables are set as required
5. I use Android Studio 3.4.1
6. Windows 10 Professional, 64 Bit

Build Output
********************************************************************************************

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

SIMPLE: Build command failed.

SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.

ERROR: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
Open File

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :opencv.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :opencv.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :opencv.
Show Details
Affected Modules: app

********************************************************************************************

**Comment by ramvdixit** [comment]
Ok. After hard-coding  the OpenCV SDk, the error shifted to the Eigen Path. So I hard-coded both the values. Another error was that the minSdkVersion was defined in the Manifest and I removed it. Now I have the following error:

*****************************************************************************************

SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: md "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\armeabi-v7a" >NUL 2>NUL || rem


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi] E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdbserver"


SIMPLE: copy /b/y "C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\build\\..\prebuilt\android-arm\gdbserver\gdbserver" "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\armeabi-v7a\gdbserver" > NUL


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbsetup       ": "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup"


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a" > E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/support C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include "C:/OpenCV-android-sdk/sdk/native/jni/include/opencv" "C:/OpenCV-android-sdk/sdk/native/jni/include" C:/eigen3/eigen-eigen-b3f3d4950030 E:/HDev2/fra/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include" >> E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/x86_64/objs/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: md "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"


SIMPLE: copy /b/y "C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86" > E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/support C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include "C:/OpenCV-android-sdk/sdk/native/jni/include/opencv" "C:/OpenCV-android-sdk/sdk/native/jni/include" C:/eigen3/eigen-eigen-b3f3d4950030 E:/HDev2/fra/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include" >> E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/arm64-v8a/objs/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/x86/objs/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: md "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\x86_64" >NUL 2>NUL || rem


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86_64] "Gdbserver      ": "[x86_64-linux-android] E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86_64/gdbserver"


SIMPLE: copy /b/y "C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\build\\..\prebuilt\android-x86_64\gdbserver\gdbserver" "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\x86_64\gdbserver" > NUL


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86_64] "Gdbsetup       ": "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86_64/gdb.setup"


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64" > E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86_64/gdb.setup


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include "C:/OpenCV-android-sdk/sdk/native/jni/include/opencv" "C:/OpenCV-android-sdk/sdk/native/jni/include" C:/eigen3/eigen-eigen-b3f3d4950030 E:/HDev2/fra/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include" >> E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/x86_64/gdb.setup


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/face-lib//face-lib.o'.  Stop.


SIMPLE: Build command failed.


SIMPLE: Error while executing process C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\HDev2\fra\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


SIMPLE: md "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\arm64-v8a" >NUL 2>NUL || rem


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [arm64-v8a] "Gdbserver      ": "[aarch64-linux-android] E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdbserver"


SIMPLE: copy /b/y "C:\Users\sysfore\AppData\Local\Android\Sdk\ndk-bundle\build\\..\prebuilt\android-arm64\gdbserver\gdbserver" "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib\arm64-v8a\gdbserver" > NUL


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [arm64-v8a] "Gdbsetup       ": "E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdb.setup"


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a" > E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdb.setup


SIMPLE: C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include "C:/OpenCV-android-sdk/sdk/native/jni/include/opencv" "C:/OpenCV-android-sdk/sdk/native/jni/include" C:/eigen3/eigen-eigen-b3f3d4950030 E:/HDev2/fra/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include C:/Users/sysfore/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include" >> E:\HDev2\fra\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdb.setup


SIMPLE: process_begin: CreateProcess(NULL, "", ...) failed.


SIMPLE: make: *** No rule to make target `/face-lib.cpp', needed by `E:/HDev2/fra/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/face-lib//face-lib.o'.  Stop.

************************************************************************************************

**Comment by ramvdixit** [comment]
OK. The new version 1.2.3 solved it. I see that the OpenCV SDK and Eigen3 are bundled into the package. Thanks for the updated version. Keep up the excellent work. Closing the issue.

**Comment by Lauszus** [comment]
Good to hear that you solved the issue.

I have now documented how to apply the OpenCV patch in the README: https://github.com/Lauszus/FaceRecognitionApp/commit/a90e443b24e5a8f92a395b35a4e4e8e66879879d.
