### ISSUE TITLE
Error:(20, 10) 'Eigen/Dense' file not found

### ISSUE THREAD

**Issue by jheimes-silveira** [Lauszus/FaceRecognitionApp#5]
Hi, I downloaded the modules following all the steps and put the environment variables right, but still not finding my content
![image](https://cloud.githubusercontent.com/assets/16032899/23827723/9fc0dc36-0698-11e7-94e8-01745e2ee0b2.png)

**Comment by Lauszus** [comment]
@jheimes-silveira what does ```echo $OPENCV_ANDROID_SDK $EIGEN3_DIR``` print?

**Comment by jheimes-silveira** [comment]
I found the problem, I updated the EIGEN3_DIR repository for the last version and it worked, thank you very much, I loved your work and it is very helpful for me to be able to build my own.

**Comment by Lauszus** [comment]
You're welcome. Glad you appreciate my work!
