### ISSUE TITLE
Local host

### ISSUE THREAD

**Issue by MustafaDar** [Lauszus/FaceRecognitionApp#50]
Is it possible to send the training data stored in your project to a server?

**Comment by Lauszus** [comment]
@MustafaDar all the images are stored in the ```images``` array and the labels are stored in ```imagesLabels```. However you probably want to send the image data to the server as a Matrix - check out how ```imagesMatrix``` is calculated.

Another option would be convert the images to file and then transfer the file to the server - check out the ```SaveImage``` function.
