### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shixin398** [Lauszus/FaceRecognitionApp#53]
Executing tasks: [:app:assembleDebug] in project D:\code\AndroidStudioProject\Github\FaceRecognitionApp

WARNING: ABIs [armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.
WARNING: ABIs [armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.
D:\code\AndroidStudioProject\Github\FaceRecognitionApp\app\src\main\cpp\Android.mk:6: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.
D:\code\AndroidStudioProject\Github\FaceRecognitionApp\app\src\main\cpp\Android.mk:6: *** Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory.  Stop.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :opencv.
     Required by:
         project :app
      > Unable to find a matching configuration of project :opencv: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by Lauszus** [comment]
@shixin398 you need set environmental variables `OPENCV_ANDROID_SDK` and `EIGEN3_DIR` in `settings.gradle` and `Android.mk` to be set to the path of the OpenCV Android SDK and Eigen3 libraries.

This is also described in the README: https://github.com/Lauszus/FaceRecognitionApp#advanced-build-instructions.

Alternatively you can just download the latest release: https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.3/FaceRecognitionApp-1.2.3.zip and import it into Android Studio.

**Comment by Lauszus** [comment]
Closing due to lack of response.
