### ISSUE TITLE
Recognizing every thing as known Label

### ISSUE THREAD

**Issue by Faizanshah21** [Lauszus/FaceRecognitionApp#55]
The application on the app store as well as this code has the issue of recognizing everything as a known label. When you save a face with a picture and test it afterward. It keeps on asking to choose the saved label for further training.

**Comment by Lauszus** [comment]
@Faizanshah21 that is by design. The name shown is the best guess. Every time you click on the name you make the "guess" better. If you don't want that you can simply fork it and write you own application that suit your needs.
