### ISSUE TITLE
Help me build this app

### ISSUE THREAD

**Issue by starzs3cret** [Lauszus/FaceRecognitionApp#56]
In Android studio 4.0 and now era Android X library, and etc. I can't build this project. NDK 21.3.6528147, using same opencv and eigen. setting environment variable is done. still return error NDK aborting .. stop. Can someone explaining how to build this project? thanks.

**Comment by furqanyasin** [comment]
> In Android studio 4.0 and now era Android X library, and etc. I can't build this project. NDK 21.3.6528147, using same opencv and eigen. setting environment variable is done. still return error NDK aborting .. stop. Can someone explaining how to build this project? thanks.

I double-checked that I already had the latest NDK installed (so that wasn't the solution for me). Next I did the following: Android Studio Menu -> **File -> Project structure -> SDK Location**. Here, no NDK was selected, so I selected the latest version. This solved the problem.

**Comment by Lauszus** [comment]
This app was tested with Android NDK r18, so please try that version if you are still having issues.

**Comment by Lauszus** [comment]
Closing due to lack of response.
