### ISSUE TITLE
all conditions are wrong in this file "FaceRecognitionApp/app/src/main/cpp/Android.mk"

### ISSUE THREAD

**Issue by furqanyasin** [Lauszus/FaceRecognitionApp#57]
I'm using ubantu everything is working but only "FaceRecognitionApp/app/src/main/cpp/Android.mk" this file containing errors
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ifndef OPENCV_ANDROID_SDK //error 1
  $(error Please specify environmental variable OPENCV_ANDROID_SDK to OpenCV Android SDK directory)
endif

OPENCV_INSTALL_MODULES := on
include $(OPENCV_ANDROID_SDK)/sdk/native/jni/OpenCV.mk

ifndef EIGEN3_DIR //error 2
  $(error Please specify environmental variable EIGEN3_DIR to Eigen 3 directory)
endif

LOCAL_MODULE := face-lib
LOCAL_SRC_FILES += $(LOCAL_PATH)/face-lib.cpp $(LOCAL_PATH)/FaceRecognitionLib/Facebase.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/Eigenfaces.cpp $(LOCAL_PATH)/FaceRecognitionLib/Fisherfaces.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/PCA.cpp $(LOCAL_PATH)/FaceRecognitionLib/LDA.cpp
LOCAL_C_INCLUDES += $(EIGEN3_DIR)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/FaceRecognitionLib/RedSVD/include
LOCAL_LDLIBS += -llog -ldl
LOCAL_CPPFLAGS += -std=gnu++11 -frtti -fexceptions

include $(BUILD_SHARED_LIBRARY)

**Comment by Lauszus** [comment]
This is documented in the build instructions: https://github.com/Lauszus/FaceRecognitionApp#build-instructions.

Either you have to specify the `OPENCV_ANDROID_SDK` and `EIGEN3_DIR` and environmental variables or hardcode the paths.

For now I would recommend you download the latest release where OpenCV and Eigen3 are bundled: https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.3/FaceRecognitionApp-1.2.3.zip.

**Comment by furqanyasin** [comment]
> This is documented in the build instructions: https://github.com/Lauszus/FaceRecognitionApp#build-instructions.
> 
> Either you have to specify the `OPENCV_ANDROID_SDK` and `EIGEN3_DIR` and environmental variables or hardcode the paths.
> 
> For now I would recommend you download the latest release where OpenCV and Eigen3 are bundled: https://github.com/Lauszus/FaceRecognitionApp/releases/download/1.2.3/FaceRecognitionApp-1.2.3.zip.

yes, thanks for sharing, I solved this , Many thanks
