### ISSUE TITLE
Build errors Facebase.o': 'No such file or directory'

### ISSUE THREAD

**Issue by Tejpalsb** [Lauszus/FaceRecognitionApp#58]
I am getting errors while building this project as
unable to open output file  ..../app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'

& 

Build command failed.
Error while executing process E:\AndroidSDK\ndk\21.3.6528147\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\TejpalData\FaceRecognitionApp-1.2.3\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=E:\TejpalData\FaceRecognitionApp-1.2.3\app\src\main\cpp\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=E:/TejpalData/facedetection/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\TejpalData\FaceRecognitionApp-1.2.3\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null E:/TejpalData/FaceRecognitionAttendance/facedetection/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86/libface-lib.so}
[x86] Compile++      : face-lib <= face-lib.cpp
[x86] Compile++      : face-lib <= Facebase.cpp
error: unable to open output file 'E:/TejpalData/FaceRecognitionAttendance/facedetection/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/face-lib/E_/TejpalData/FaceRecognitionAttendance/facedetection/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Facebase.o': 'No such file or directory'
1 error generated.
make: *** [E:/AndroidSDK/ndk/21.3.6528147/build//../build/core/build-binary.mk:478: E:/TejpalData/FaceRecognitionAttendance/facedetection/FaceRecognitionApp-1.2.3/app/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/face-lib/E_/TejpalData/FaceRecognitionAttendance/facedetection/FaceRecognitionApp-1.2.3/app/src/main/cpp/FaceRecognitionLib/Facebase.o] Error 1

**Comment by Lauszus** [comment]
From the output it looks like you have created your own app named `FaceRecognitionAttendance` and is trying to include this one into it.

Anyway the error seems to be because you have not cloned the submodule, as described in the README. Here's the command to do so:

```bash
git submodule update --init --recursive
```

**Comment by Lauszus** [comment]
Closing due to lack of response.
