### ISSUE TITLE
NullPointerException happened

### ISSUE THREAD

**Issue by masa126** [Lauszus/FaceRecognitionApp#59]
Hi Lauszus,
When I build FaceRecognitionApp-1.2.3 with Android Studio 4.1, Java.NullPointerException happened in app.
I specified OpenCV sdk 343 and Eigen3.2.10 in the project structure, selected android SDK as 28, gradle plugin as 3.2.1 and gradle version 4.6.
Will you kindly suggest me the way to solve this issue?

**Comment by Lauszus** [comment]
Please use OpenCV 3.4.1 and Eigen3 3.3.5, as described in the README: https://github.com/Lauszus/FaceRecognitionApp#advanced-build-instructions
