### ISSUE TITLE
Repository eigen/eigen not found

### ISSUE THREAD

**Issue by owentan19** [Lauszus/FaceRecognitionApp#60]
I need help, please

This link(https://bitbucket.org/eigen/eigen/get/3.3.5.zip) is not found

**Comment by Lauszus** [comment]
Thanks. I just fixed the links.

You can download Eigen 3.3.5 from here: <https://gitlab.com/libeigen/eigen/-/archive/3.3.5/eigen-3.3.5.zip>.
