### ISSUE TITLE
Hi I have some issue plz solve my issues to create app

### ISSUE THREAD

**Issue by Milyasoffical** [Lauszus/FaceRecognitionApp#61]
I want loan app but many problems appear I don't understand how I solve plz help me to solve my problem same layout

**Comment by Lauszus** [comment]
Please provide some more information. What errors are you getting? Please copy paste them into this issue.

Did you follow the build instructions: https://github.com/Lauszus/FaceRecognitionApp#build-instructions?

**Comment by Lauszus** [comment]
Closing due to lack of response.
