### ISSUE TITLE
Can not recognize face with FaceRecognitionApp-1.2.apk

### ISSUE THREAD

**Issue by devillee** [Lauszus/FaceRecognitionApp#8]
Hi ,I have downloaded the FaceRecognitionApp-1.2.apk, and take photo of my face, but it cannot recognize my face.

**Comment by Lauszus** [comment]
The algorithm is far from perfect. Please note that Eigenfaces and Fisherfaces are not state of the art. If you want to get a higher success-rate you should look into machine learning or similar.

Please also have a look at the two reports we wrote: [Eigenfaces\_Report.pdf](https://github.com/Lauszus/FaceRecognitionLib/raw/master/Eigenfaces_Report.pdf) and [Final\_Project\_Report.pdf](https://github.com/Lauszus/FaceRecognitionLib/raw/master/Final_Project_Report.pdf).
