### ISSUE TITLE
setup problem in windows

### ISSUE THREAD

**Issue by shivam21** [Lauszus/FaceRecognitionApp#9]
where to execute these commands.I tried it in cmd but it says wget command not found?

wget https://github.com/opencv/opencv/releases/download/3.2.0/opencv-3.2.0-android-sdk.zip -O opencv-android-sdk.zip
unzip opencv-android-sdk.zip
wget https://bitbucket.org/eigen/eigen/get/3.3.3.zip -O Eigen3.zip
unzip Eigen3.zip

**Comment by yohanes-ai** [comment]
You need install wget first, after that you can run that command. If you're working on Windows machine, get  wget from this [link](http://gnuwin32.sourceforge.net/packages/wget.htm). Otherwise, on linux environment you can download it from [here](https://www.gnu.org/software/wget/]). In my case on centos environment do the things like this `yum install wget`

Happy codding

**Comment by shivam21** [comment]
Thanks for such a quick reply.but now it says : 
 Error:(20, 10) fatal error: 'Eigen/Dense' file not found
even I tried hardcoding the path.here is my Android.mk

    LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

OPENCV_INSTALL_MODULES := on
include C:\Users\BHUSRI\Desktop\OpenCV-android-sdk\sdk\native\jni/OpenCV.mk

LOCAL_MODULE := face-lib
LOCAL_SRC_FILES += $(LOCAL_PATH)/face-lib.cpp $(LOCAL_PATH)/FaceRecognitionLib/Facebase.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/Eigenfaces.cpp $(LOCAL_PATH)/FaceRecognitionLib/Fisherfaces.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/PCA.cpp $(LOCAL_PATH)/FaceRecognitionLib/LDA.cpp
LOCAL_C_INCLUDES += C:\Users\BHUSRI\Desktop\eigen3\Eigen $(LOCAL_PATH)/FaceRecognitionLib/RedSVD/include
LOCAL_LDLIBS += -llog -ldl
LOCAL_CPPFLAGS += -std=gnu++11 -frtti -fexceptions

include $(BUILD_SHARED_LIBRARY)

**Comment by Lauszus** [comment]
@JhonImmanuel thanks for helping out!

**Comment by Lauszus** [comment]
For others looking at this issue, you do not really need wget. Just simply download the two zip-archives by clicking on the links.
